name: Build OpenCV for iOS and iOS Simulator

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        brew install cmake ninja ant
        python3 -m pip install numpy

    - name: Download OpenCV source
      run: |
        git clone https://github.com/opencv/opencv.git

    - name: Build OpenCV for iOS and iOS Simulator
      run: |
        python3 opencv/platforms/ios/build_framework.py ios --iphoneos_archs arm64 --iphonesimulator_archs x86_64

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: opencv-ios
        path: ios
